### ISSUE TITLE
How to print the google colab output?

### ISSUE THREAD

**Issue by Manuservus11** [Samyak2/Keep-Colab-Alive#2]
I want to print the output. I don't now how to do that. Can you send my the python code snippet?

**Comment by Samyak2** [comment]
After line number 148,
https://github.com/Samyak2/Keep-Colab-Alive/blob/35910f465790d0989fb60096f73e416c5a017625/keep_colab_alive.py#L147-L150
The following snippet should work to get the code output.
```python
iframe = driver.find_element_by_xpath(f"//div[@id='{cell}']//iframe")
driver.switch_to.frame(iframe)
output_element = driver.find_element_by_xpath('//div[@id="output-body"]')
cell_output = output_element.text
print(f"Output of cell {cell}:")
print(f"\t{cell_output}")
driver.switch_to.default_content()
```

I have not tested it, let me know if it works.

**Comment by Manuservus11** [comment]
It works. 
Thanks
