### ISSUE TITLE
I got this to work on Google Chrome and the new AI police

### ISSUE THREAD

**Issue by mathemusician** [Samyak2/Keep-Colab-Alive#3]
Hi! So I got your script to work on Google Chrome, and it's updated to adapt with the stricter AI that Google Colab has implemented March of this year. The previous scripts employed on medium and hackernoon don't work anymore. Now I don't know how wise it would be to make this open source, but hey, why not? Pull request, maybe?

**Comment by Samyak2** [comment]
Unless you're using some really questionable techniques, why not make it open source? XD

Though I'm not sure if I want to maintain this project further. You can maintain your own fork of this if you wish, the license allows for it. Ofcourse if you don't want that, you can send a PR, I'll merge it eventually.

**Comment by mathemusician** [comment]
You've convinced me; I'm sure this project is far from questionable. *wink* I'll send you a PR soon after I make sure it works on windows

**Comment by Samyak2** [comment]
@mathemusician don't mean to bother you, but any progress? xD
